### ISSUE TITLE
Flash save is unreliable with a slightly-old battery.

### ISSUE THREAD

**Issue by myklemykle** [schollz/pikocore-src#5]
When using pikocore with a rechargeable AAA battery I often found that trying to save my pattern causes the board to hang. And it seems to be the same kind of hang I get when the battery is finally too low to power the pico. But the hang-while-saving happens much sooner in the life cycle of the battery, when everything else still seems to be functioning well.  Meanwhile, I never see this happen when piko is powered by USB.

I have been experimenting with this using my bench power supply to simulate the battery. It looks like when voltage gets below 1.4v, writes to flash become a bit flaky; they start, but don't always finish. When it gets down to 1.3v, it's pretty unreliable, and can even corrupt flash to the point that I can't boot until I re-flash the firmware.  The rest of piko still operates fine at those voltages.

Saving to flash appears to raise current consumption by 5-6ma. (Although maybe more than half of that is used by the RGB LED? It seems to use roughly 1-3ma, depending on color?) The problem seems triggered by low voltage more than low current, but on an AAA one will lead to the other I think.

**Comment by schollz** [comment]
@myklemykle what kind of AAA battery are you using? I've had reports that carbon zinc / recharagable are more likely to easily drop to 1.4v. The best I've found are the alkaline or good quality AAA batteries.

**Comment by myklemykle** [comment]
I've been using a rechargeable NiCad. Maybe that's just not supported. Is there anything about specific battery types in the doc?

**Comment by schollz** [comment]
I suggest trying an alkaline battery then! https://infinitedigits.co/wares/pikocore/#the-battery-dies-really-quickly

**Comment by myklemykle** [comment]
OK.
